## Comment out features you don't want

# These are required
consumer_key: "qahZsNer1hup8ZhX8lLlqB1ub"
consumer_secret: "WT5NvXiI5igOPzJ8dw3pDtyF0S0ppNNLtTrh6UoT5kRtXjIsKa"
access_token: "885210636904529920-nlGSFhdUmv8GGUPQIGbyzTosOjCxdGa"
access_token_secret: "S4ykNnt6HDSBc0qxFYJCDde1ThOTh3NguCHyAYxmiBz0Y"

# retweet filters
friends_limit: 100 # user has at least this many friends
favourites_limit: 1000 # user has at least this many favourites
followers_limit: 100 # user has at least this many followers
statuses_limit: 1000 # user has at least this many status updates
retweeted_limit: False # will cause some extra searches if set, shit may not even ever work
                       # would have to be a number < 5
                       # checks for how many times the tweet has already been retweeted


# relative to time zone on machine running bot
# 10:00 - 22:00
minimum_hour: 10
maximum_hour: 22

# optional path to tweets to send out on intervals
tweets_path: 'tweets.txt'


## THE BELOW CONFIGURATIONS ARE CASE INSENSITIVE :)

# hashtags to search for and retweet
watched_hashtags:
  - "#NetNeutrality"
  - "#LogOff"

# hashtags to ignore if they get found in a returned tweet
blocked_hashtags:
  - "#butthurtassholes"
  - "#otherdouschers"

# user mentions to ignore if they get found in a returned tweet
blocked_user_mentions:
  - "@SomeDick"
  - "@CyberDildo"

 # ignore tweets with these phrases that trigger you
trigger_phrases:
  - "I slept with urnan last night"

log_level: "debug"

# Sleep intervals
retweet_sleep: 600
tweet_sleep: 1500

config_reload_time: 60
tweets_reload_time: 60
